### ISSUE TITLE
I came here searching for the opposite...

### ISSUE THREAD

**Issue by arvidjohansen** [knowsuchagency/promptic#1]
.. but stayed after scrolling up and down a couple of times in the readme

and gradually realizing...

- this is pretty cool
- tasteful use of modern python syntax  
- intuitive level of abstraction

I prefer 5 levels of indentation over 5 hierarchies of call stacks any day

good job

**Comment by knowsuchagency** [comment]
Thanks for the kind words -- I feel the same way about indentation vs call stacks. This library grew out of my own frustration with other abstractions
