### ISSUE TITLE
Simultaneous Streaming + Function Calls?

### ISSUE THREAD

**Issue by not-an-llm** [knowsuchagency/promptic#3]
Very cool! This is a great level of abstraction.

It looks like function calls/tool use is mutually exclusive with streaming:

https://github.com/knowsuchagency/promptic/blob/main/promptic.py#L164-L170

wondering if you have plans on making it possible to stream responses for tool-enabled chats? If the model decides not to use a tool, then stream right away. If the model decides to call a function or multiple functions, then collect and yield the functions as they stream in

**Comment by knowsuchagency** [comment]
Great point thanks @not-an-llm ! Added in #4
